//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sam {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class SamUserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SamUserSettings defaultInstance = ((SamUserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SamUserSettings())));
        
        public static SamUserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPT_API_KEY {
            get {
                return ((string)(this["GPT_API_KEY"]));
            }
            set {
                this["GPT_API_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You are a helpful assistant.")]
        public string DefaultAgentPersonality {
            get {
                return ((string)(this["DefaultAgentPersonality"]));
            }
            set {
                this["DefaultAgentPersonality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgentSettingsList {
            get {
                return ((string)(this["AgentSettingsList"]));
            }
            set {
                this["AgentSettingsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default_agents.csv")]
        public string AgentSettingsFileLocation {
            get {
                return ((string)(this["AgentSettingsFileLocation"]));
            }
            set {
                this["AgentSettingsFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AZURE_API_KEY {
            get {
                return ((string)(this["AZURE_API_KEY"]));
            }
            set {
                this["AZURE_API_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AZURE_TTS_REGION {
            get {
                return ((string)(this["AZURE_TTS_REGION"]));
            }
            set {
                this["AZURE_TTS_REGION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AZURE_TTS_VOICE {
            get {
                return ((string)(this["AZURE_TTS_VOICE"]));
            }
            set {
                this["AZURE_TTS_VOICE"] = value;
            }
        }
    }
}
